# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtGui import QBrush,QPixmap
from img_system import shuiyin # 导入模块


class Ui_MainWindow(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        #设置菜单栏
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")

        #添加主菜单栏
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menubar.setObjectName("menu")

        #设置关于栏
        self.menu2 = QtWidgets.QMenu(self.menubar)
        self.menu2.setObjectName("menu2")

        #添加子菜单添加水印
        self.actionMark = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()#设置图标对象
        icon.addPixmap(QtGui.QPixmap('./img/mark.ico'),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionMark.setIcon(icon)
        self.actionMark.setObjectName("actionMark")


        self.menu.addAction(self.actionMark)
        self.menubar.addAction(self.menu.menuAction())

        self.about = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap('./img/about.ico'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about.setIcon(icon2)
        self.about.setObjectName("about")
        self.menu2.addAction(self.about)
        self.menubar.addAction(self.menu2.menuAction())

        #设置窗体背景
        background = QtGui.QPalette()
        background.setBrush(MainWindow.backgroundRole(),QBrush(QPixmap("./img/back.jpg").scaled(MainWindow.size(),QtCore.Qt.IgnoreAspectRatio,QtCore.Qt.SmoothTransformation)))
        MainWindow.setPalette(background)
        MainWindow.setAutoFillBackground(True)# 设置自动填充背景

        # 禁止显示最大化按钮及调整窗体大小
        MainWindow.setFixedSize(800,600)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图片水印系统"))

        #设置菜单名称
        self.menu.setTitle(_translate("MainWindow", "主菜单"))
        self.menu2.setTitle(_translate("MainWindow", "关于"))
        self.actionMark.setText(_translate("MainWindow", "添加水印"))
        self.about.setText(_translate("MainWindow", "关于"))

        #关联菜单(信号和槽)
        self.actionMark.triggered.connect(self.openMark)
        # self.rename.triggered.connect(self.openRename)
        self.about.triggered.connect(self.openAbout)

    def openMark(self):
        self.newWindow = shuiyin.Ui_MarkWindow()
        self.newWindow.show()

    def openAbout(self):
        title = '关于本软件'
        text =          '图片管理系统是一款方便批量处理图片的工具软件，' \
                        '该软件可以方便的为图片添加文字水印和图片水印，' \
                        '还可以自定义添加位置，以及透明度；' \
                        '另外还可以通过该软件对图片文件进行重命名，' \
                        '支持文件名大写、小写，以及根据自定义模板对图片文件进行编号。'
        QMessageBox.information(None,title,text,QMessageBox.Ok)

if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
